jobs:
- job: 'build'
  timeoutInMinutes: 120
  workspace:
    clean: all
  steps:
  - script: '/usr/bin/python3 -m pip install -r tools/ci_build/github/linux/docker/scripts/requirements.txt'
    displayName: 'Install python packages'

  - task: PythonScript@0
    displayName: 'Generate cmake config'
    inputs:
      scriptPath: 'tools/ci_build/build.py'
      arguments: '--build_dir $(Build.BinariesDirectory) --config Release --skip_submodule_sync --enable_onnx_tests --parallel --build_shared_lib --enable_pybind --use_nuphar --update'
      pythonInterpreter: /usr/bin/python3
  - task: PythonScript@0
    displayName: 'Build'
    inputs:
      scriptPath: 'tools/ci_build/build.py'
      arguments: '--build_dir $(Build.BinariesDirectory) --config Release --skip_submodule_sync --enable_onnx_tests --parallel --build_shared_lib --enable_pybind --use_nuphar --build'
      pythonInterpreter: /usr/bin/python3
  - task: PythonScript@0
    displayName: 'Test'
    inputs:
      scriptPath: 'tools/ci_build/build.py'
      arguments: '--build_dir $(Build.BinariesDirectory) --config Release --skip_submodule_sync --enable_onnx_tests --parallel --build_shared_lib --enable_pybind --use_nuphar --test'
      pythonInterpreter: /usr/bin/python3
  - template: templates/component-governance-component-detection-steps.yml
    parameters :
      condition : 'succeeded'